require('./helpers')

require('./vueAdmin')
require('./vueAdminElected')
require('./vueAdminContest')
require('./vueAdminContestVotes')
require('./vueCongressmen')
require('./vueSeeduc')
require('./vueUsers')
//require('./vueFilters')
require('./vueSubscribe')
require('./vueGallery')
require('./vueMap')
require('./vueSchools')
require('./vueVoteStatistics')
require('./vueTimeline')
